<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.maas</groupId>
        <artifactId>graal-base</artifactId>
        <version>2025.01-SNAPSHOT</version>
    </parent>
    <groupId>nl.maas.filerenamer</groupId>
    <artifactId>filerenamer</artifactId>
    <packaging>pom</packaging>
    <version>2025.01-SNAPSHOT</version>

    <modules>
        <module>filerenamer-backend</module>
        <module>filerenamer-frontend</module>
    </modules>

    <scm>
        <connection>scm:git:ssh://git@bitbucket.org/mmaas/fx_analyzer.git
        </connection>
        <developerConnection>scm:git:ssh://git@bitbucket.org/mmaas/fx_analyzer.git
        </developerConnection>
        <url>https://mmaas@bitbucket.org/mmaas/filerenamer.git
        </url>
    </scm>

    <properties>
    </properties>

    <repositories>
        <repository>
            <id>objectdb</id>
            <name>ObjectDB Repository</name>
            <url>https://m2.objectdb.com</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>${maven-assembly-plugin.version}</version>
                    <configuration>
                        <appendAssemblyId>false</appendAssemblyId>
                        <finalName>bank-book-${project.version}</finalName>
                        <descriptors>
                            <descriptor>${basedir}/assembly.xml</descriptor>
                        </descriptors>
                    </configuration>
                    <executions>
                        <execution>
                            <id>create-archive</id>
                            <phase>package</phase>
                            <goals>
                                <goal>single</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
        </plugins>
    </build>
</project>
